// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Footer → link*
 */
export interface FooterDocumentDataLinkItem {
  /**
   * text link field in *Footer → link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.link[].text_link
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text_link: prismic.KeyTextField;

  /**
   * link field in *Footer → link*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.link[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Texte field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * Copyright field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: © 2026 Offres d'emploi
   * - **API ID Path**: footer.copyright
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copyright: prismic.KeyTextField;

  /**
   * link field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.link[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  link: prismic.GroupField<Simplify<FooterDocumentDataLinkItem>>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HeaderDocumentDataSlicesSlice = LogoSlice;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * Nom du site field in *Header*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Offres d'emploi
   * - **API ID Path**: header.site_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_name: prismic.KeyTextField;

  /**
   * Couleur du header field in *Header*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: header.background_color
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  background_color: prismic.ColorField;

  /**
   * Slices field in *Header*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: header.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Titre field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Content for Liste des offres documents
 */
interface JobListDocumentData {
  /**
   * Titre field in *Liste des offres*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_list.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Liste des offres*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_list.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Liste des offres document from Prismic
 *
 * - **API ID**: `job_list`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type JobListDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<JobListDocumentData>,
    "job_list",
    Lang
  >;

/**
 * Item in *Offre d'emploi → Emails administrateurs*
 */
export interface JobOfferDocumentDataAdminEmailsItem {
  /**
   * Email field in *Offre d'emploi → Emails administrateurs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: admin@example.com
   * - **API ID Path**: job_offer.admin_emails[].email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;
}

/**
 * Content for Offre d'emploi documents
 */
interface JobOfferDocumentData {
  /**
   * Titre field in *Offre d'emploi*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_offer.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Entreprise field in *Offre d'emploi*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Nom de l'entreprise
   * - **API ID Path**: job_offer.company
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company: prismic.KeyTextField;

  /**
   * Lieu field in *Offre d'emploi*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Paris, Remote...
   * - **API ID Path**: job_offer.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * Type de contrat field in *Offre d'emploi*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: job_offer.contract_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  contract_type: prismic.SelectField<
    "CDI" | "CDD" | "Alternance" | "Stage" | "Freelance"
  >;

  /**
   * Date de publication field in *Offre d'emploi*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: job_offer.published_at
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  published_at: prismic.DateField;

  /**
   * Offre disponible field in *Offre d'emploi*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: job_offer.is_available
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  is_available: prismic.BooleanField;

  /**
   * Emails administrateurs field in *Offre d'emploi*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: job_offer.admin_emails[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  admin_emails: prismic.GroupField<
    Simplify<JobOfferDocumentDataAdminEmailsItem>
  >;

  /**
   * Résumé field in *Offre d'emploi*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_offer.excerpt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  excerpt: prismic.RichTextField;

  /**
   * Contenu de l'offre field in *Offre d'emploi*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: job_offer.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Offre d'emploi document from Prismic
 *
 * - **API ID**: `job_offer`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type JobOfferDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<JobOfferDocumentData>,
    "job_offer",
    Lang
  >;

export type AllDocumentTypes =
  | FooterDocument
  | HeaderDocument
  | HomepageDocument
  | JobListDocument
  | JobOfferDocument;

/**
 * Primary content in *Logo → Default → Primary*
 */
export interface LogoSliceDefaultPrimary {
  /**
   * Logo field in *Logo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Logo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Logo du site.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LogoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Logo*
 */
type LogoSliceVariation = LogoSliceDefault;

/**
 * Logo Shared Slice
 *
 * - **API ID**: `logo`
 * - **Description**: Logo affiché dans le header.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LogoSlice = prismic.SharedSlice<"logo", LogoSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataLinkItem,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      JobListDocument,
      JobListDocumentData,
      JobOfferDocument,
      JobOfferDocumentData,
      JobOfferDocumentDataAdminEmailsItem,
      AllDocumentTypes,
      LogoSlice,
      LogoSliceDefaultPrimary,
      LogoSliceVariation,
      LogoSliceDefault,
    };
  }
}
